// Generated by CoffeeScript 1.6.3
(function() {
  var CircleTool, Tool,
      __hasProp = {}.hasOwnProperty,
      __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tool = MarkingSurface.Tool;

  CircleTool = (function(_super) {
    __extends(CircleTool, _super);

    CircleTool.prototype.handleRadius = CircleTool.mobile ? 5 : 5;

    CircleTool.prototype.strokeWidth = 2;

    CircleTool.prototype.defaultRadius = 5;

    CircleTool.prototype.startOffset = null;

    function CircleTool() {
      CircleTool.__super__.constructor.apply(this, arguments);
      this.mark.x = 0;
      this.mark.y = 0;
      this.mark.r = 0;

      // 从test.html获取当前的maskMode
      if (typeof maskMode !== 'undefined') {
        this.mark.mode = maskMode;
      } else {
        this.mark.mode = 'maskInner'; // 默认值
      }

      this.mark.id = 'circle_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9); // 唯一ID

      this.outline = this.addShape('circle.outline', {
        fill: 'transparent',
        stroke: 'currentColor'
      });

      this.radiusHandle = this.addShape('circle.radius-handle', {
        fill: 'currentColor'
      });

      this.addEvent('marking-surface:element:start', '.outline', this.startDrag);
      this.addEvent('marking-surface:element:move', '.outline', this.moveOutline);
      this.addEvent('marking-surface:element:move', '.radius-handle', this.dragRadiusHandle);
    }

    // 在圆形工具开始绘制时被调用。设置圆的初始位置和大小
    CircleTool.prototype.onInitialStart = function(e) {
      var x, y, _ref;
      CircleTool.__super__.onInitialStart.apply(this, arguments);
      _ref = this.coords(e), x = _ref.x, y = _ref.y;
      return this.mark.set({
        x: x,
        y: y,
        r: this.defaultRadius
      });
    };

    // 在圆形工具开始移动时被调用。更新圆的大小
    CircleTool.prototype.onInitialMove = function(e) {
      CircleTool.__super__.onInitialMove.apply(this, arguments);
      return this.dragRadiusHandle(e);
    };

    // 在用户开始拖动圆形时被调用。存储起始偏移量
    CircleTool.prototype.startDrag = function(e) {
      var x, y, _ref;
      _ref = this.coords(e), x = _ref.x, y = _ref.y;
      return this.startOffset = {
        x: this.mark.x - x,
        y: this.mark.y - y
      };
    };

    // 在用户拖动圆形时被调用。更新圆的位置
    CircleTool.prototype.moveOutline = function(e) {
      var x, y, _ref;
      _ref = this.coords(e), x = _ref.x, y = _ref.y;
      return this.mark.set({
        x: x + this.startOffset.x,
        y: y + this.startOffset.y
      });
    };

    // 在用户拖动半径控制点时被调用。更新圆的大小
    CircleTool.prototype.dragRadiusHandle = function(e) {
      var x, y, _ref;
      _ref = this.coords(e), x = _ref.x, y = _ref.y;
      return this.mark.set({
        r: this.getDistance(this.mark.x, this.mark.y, x, y)
      });
    };

    // 在圆形工具需要重新渲染时被调用。更新圆的外观
    CircleTool.prototype.render = function() {
      var handleRadius, scale, strokeWidth, _ref, _ref1, _ref2;
      CircleTool.__super__.render.apply(this, arguments);
      scale = (((_ref = this.markingSurface) != null ? _ref.scaleX : void 0) + ((_ref1 = this.markingSurface) != null ? _ref1.scaleY : void 0)) / 2;
      strokeWidth = this.strokeWidth / scale;
      handleRadius = this.handleRadius / scale;

      // 根据mode设置颜色：inner模式为红色，outer模式为蓝色
      var color = this.mark.mode === 'maskInner' ? 'red' : 'cyan';

      this.outline.attr('strokeWidth', strokeWidth);
      this.outline.attr('stroke', color);
      this.radiusHandle.attr('r', handleRadius);
      this.radiusHandle.attr('fill', color);

      this.attr('transform', "translate(" + this.mark.x + ", " + this.mark.y + ")");

      this.outline.attr('r', this.mark.r);
      this.radiusHandle.attr('cx', this.mark.r);

      return (_ref2 = this.controls) != null ? _ref2.moveTo(this.mark) : void 0;
    };



    // 计算两点之间的距离
    CircleTool.prototype.getDistance = function(x1, y1, x2, y2) {
      var aSquared, bSquared;
      aSquared = Math.pow(x2 - x1, 2);
      bSquared = Math.pow(y2 - y1, 2);
      return Math.sqrt(aSquared + bSquared);
    };

    return CircleTool;

  })(Tool);

  if (typeof window !== "undefined" && window !== null) {
    window.MarkingSurface.CircleTool = CircleTool;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = CircleTool;
  }

}).call(this);